In [2]:
import numpy as np
numpy.__version__

'1.23.4'

In [4]:
np?

In [6]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#Creating Arrays from Python Lists
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [8]:
'''Remember that unlike Python lists, NumPy is constrained to arrays that all contain
the same type. If types do not match, NumPy will upcast if possible (here, integers are
upcast to floating point):
'''
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [9]:
np.array([1, 2, 3, 4], dtype='float32')


array([1., 2., 3., 4.], dtype=float32)

In [10]:
# nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [17]:
 # Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)
# Create a 3x5 array filled with 3.14
 np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [21]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
# Create a 3x3 array of uniformly distributed
 # random values between 0 and 1
np.random.random((3, 3))

array([[0.24967972, 0.59759412, 0.58400854],
       [0.11033718, 0.99163064, 0.98692926],
       [0.39404028, 0.47334411, 0.32276779]])

In [23]:
# Create a 3x3 array of normally distributed random values
 # with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))


array([[-0.96529481, -0.62740609,  1.0206508 ],
       [-0.57292996,  0.62052921,  0.90118441],
       [-1.00791066, -1.20946197,  0.68089372]])

In [24]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))


array([[9, 7, 4],
       [0, 8, 5],
       [5, 7, 0]])

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# Create an uninitialized array of three integers
 # The values will be whatever happens to already exist at that
 # memory location
np.empty(3)


array([1., 1., 1.])

In [32]:
#NumPy Standard Data Types
np.zeros(10, dtype='int16')
#or np.zeros(10, dtype=np.int16)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [33]:
#The Basics of NumPy Arrays
#NumPy Array Attributes
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [34]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [36]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [37]:
#Array Slicing: Accessing Subarrays x[start:stop:step]
x = np.arange(10)
x
x[:5] 

array([0, 1, 2, 3, 4])

In [38]:
x[5:]

array([5, 6, 7, 8, 9])

In [39]:
x[4:7] 

array([4, 5, 6])

In [40]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [41]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [42]:
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [43]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

In [44]:
print(x2[:, 0]) # first column of x2

[3 7 1]


In [45]:
print(x2[0, :]) # first row of x2

[3 5 2 4]


In [46]:
print(x2[0]) # equivalent to x2[0, :]

[3 5 2 4]


In [47]:
#Subarrays as no-copy views
x2_sub = x2[:2, :2]
print(x2_sub)
x2_sub[0, 0] = 99
print(x2_sub)

[[3 5]
 [7 6]]
[[99  5]
 [ 7  6]]


In [48]:
#Creating copies of arrays
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)


[[99  5]
 [ 7  6]]


In [49]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)
print(x2)

[[42  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [50]:
#Reshaping of Arrays
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
x = np.array([1, 2, 3])
# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [52]:
 # row vector via newaxis
x[np.newaxis, :]


array([[1, 2, 3]])

In [53]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [54]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [55]:
#Array Concatenation and Splitting
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [56]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [57]:
grid = np.array([[1, 2, 3],
 [4, 5, 6]])


In [58]:
np.concatenate([grid, grid])


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
np.concatenate([grid, grid], axis=1)


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [60]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
 [6, 5, 4]])
 # vertically stack the arrays
np.vstack([x, grid])


array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [61]:
y = np.array([[99],
 [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [62]:
#Splitting of arrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [63]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [64]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)


[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [65]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [68]:
#universal function (numpy)
import numpy as np
np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):

        output[i] = 1.0 / values[i]
    return output
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)


array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [69]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)
'''It takes several seconds to compute these million operations and to store the result!
When even cell phones have processing speeds measured in Giga-FLOPS (i.e., bil‐
lions of numerical operations per second), this seems almost absurdly slow. It turns
out that the bottleneck here is not the operations themselves, but the type-checking
and function dispatches that CPython must do at each cycle of the loop. Each time
the reciprocal is computed, Python first examines the object’s type and does a
dynamic lookup of the correct function to use for that type. If we were working in
compiled code instead, this type specification would be known before the code exe‐
cutes and the result could be computed much more efficiently'''

1.88 s ± 116 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [70]:
#Introducing UFuncs
print(compute_reciprocals(values))
print(1.0 / values)


[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [71]:
%timeit (1.0 / big_array)


2.41 ms ± 203 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [72]:
"""Vectorized operations in NumPy are implemented via ufuncs, whose main purpose is
to quickly execute repeated operations on values in NumPy arrays. Ufuncs are
extremely flexible—before we saw an operation between a scalar and an array, but we
can also operate between two arrays"""

'Vectorized operations in NumPy are implemented via ufuncs, whose main purpose is\nto quickly execute repeated operations on values in NumPy arrays. Ufuncs are\nextremely flexible—before we saw an operation between a scalar and an array, but we\ncan also operate between two arrays'

In [73]:
np.arange(5) / np.arange(1, 6)


array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [74]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [75]:
#Exploring NumPy’s UFuncs
#next notebook